#### Import library

In [1]:
import numpy as np
import mnist
from tensorflow import keras

#### Load the data

In [3]:
# The first time you run this might be a bit slow, since the
# mnist package has to download and cache the data.
train_images = mnist.train_images()
train_labels = mnist.train_labels()

#### Size of the dataset

In [4]:
print(train_images.shape) # (60000, 28, 28)
print(train_labels.shape) # (60000,)

(60000, 28, 28)
(60000,)


#### Transform the data

- We do this so that we can use our data to train the neuron network.
- Network input layer only accept vector (one dimension array) as input so we convert our image into the single dimension array.

In [6]:
train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()

# Normalize the images.
train_images = (train_images / 255) - 0.5
test_images = (test_images / 255) - 0.5

# Flatten the images.
train_images = train_images.reshape((-1, 784))
test_images = test_images.reshape((-1, 784))

print(train_images.shape) # (60000, 784)
print(test_images.shape)  # (10000, 784)

(60000, 784)
(10000, 784)


#### Building the Model

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
  Dense(64, activation='relu', input_shape=(784,)),
  Dense(64, activation='relu'),
  Dense(10, activation='softmax'),
])

#### Compile the model.


In [8]:
model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

#### Train the model.

In [12]:
from tensorflow.keras.utils import to_categorical
model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=5,
  batch_size=32,
)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.3584 - accuracy: 0.8913
Epoch 2/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1850 - accuracy: 0.9440
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1414 - accuracy: 0.9563
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1190 - accuracy: 0.9630
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0994 - accuracy: 0.9688


#### Test the model 

In [13]:
model.evaluate(
  test_images,
  to_categorical(test_labels)
)

313/313 [==============================] - 1s 2ms/step - loss: 0.1053 - accuracy: 0.9670


[0.10526159405708313, 0.9670000076293945]

In [14]:
# Save the model to disk.
model.save_weights('model.h5')

# Load the model from disk later using:
# model.load_weights('model.h5')

In [15]:
# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]


[7 2 1 0 4]
[7 2 1 0 4]


#### Check our predictions against the ground truths.

In [17]:
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]


#### Model summary

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                50240     
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 55,050
Trainable params: 55,050
Non-trainable params: 0
_________________________________________________________________
